# Generated by Django 3.2.9 on 2022-11-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_auto_20221115_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmodel',
            name='meter_reading',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
