# Generated by Django 3.2.9 on 2022-11-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_alter_readingmodel_meter_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingmodel',
            name='user',
        ),
    ]
