# Generated by Django 3.2.9 on 2022-11-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_remove_readingmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmodel',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
