# Generated by Django 3.2.9 on 2022-11-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_costmodel_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costmodel',
            name='user',
        ),
    ]
