# Generated by Django 3.2.9 on 2022-11-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_remove_costmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmodel',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='costmodel',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
