# Generated by Django 3.2.9 on 2022-11-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_auto_20221118_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costmodel',
            old_name='account',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='costmodel',
            old_name='hours_used',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='costmodel',
            name='details',
        ),
        migrations.RemoveField(
            model_name='costmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='costmodel',
            name='rating',
        ),
    ]
