# Generated by Django 3.2.9 on 2022-11-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_auto_20221122_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costmodel',
            name='parent',
        ),
    ]
