# Generated by Django 3.2.9 on 2022-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0025_costmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AboutModel',
        ),
    ]
