# Generated by Django 3.2.9 on 2022-11-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_auto_20221123_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmodel',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='costmodel',
            name='no_of_hours_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costmodel',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='costmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
