# Generated by Django 3.2.9 on 2022-11-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0028_roommodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmodel',
            name='consumption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
