# Generated by Django 3.2.9 on 2022-11-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0029_costmodel_consumption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costmodel',
            old_name='year',
            new_name='day',
        ),
        migrations.AddField(
            model_name='costmodel',
            name='week_ending',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
