# Generated by Django 3.2.9 on 2022-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0030_auto_20221123_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
