# Generated by Django 3.2.9 on 2022-11-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0031_costmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costmodel',
            old_name='day',
            new_name='datapoint',
        ),
        migrations.RemoveField(
            model_name='costmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='costmodel',
            name='week_ending',
        ),
    ]
