# Generated by Django 3.2.9 on 2022-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0032_auto_20221123_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costmodel',
            name='consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
