# Generated by Django 3.2.9 on 2022-11-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0033_alter_costmodel_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmodel',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
