# Generated by Django 3.2.9 on 2022-11-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0034_readingmodel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmodel',
            name='consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
