# Generated by Django 3.2.9 on 2022-11-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0035_readingmodel_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmodel',
            name='datapoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
