# Generated by Django 3.2.9 on 2022-11-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0037_auto_20221125_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='operating_condition',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
