# Generated by Django 3.2.9 on 2022-11-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0038_roommodel_operating_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmodel',
            name='parent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='panel.roommodel'),
            preserve_default=False,
        ),
    ]
