# Generated by Django 3.2.9 on 2022-11-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0003_alter_sitemodel_essay_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='electricity_bill',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='description',
            field=models.TextField(blank=True, default='Sample site description', null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='site_email',
            field=models.CharField(blank=True, default='kibebekevin@gmail.com', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='site_name',
            field=models.CharField(blank=True, default='MyAuditor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='site_url',
            field=models.URLField(blank=True, default='https://myauditor.com', null=True),
        ),
    ]
